services:
  gitops-dev:
    build: .
    restart: always
    ports:
      - "8079:8079"
    networks:
      - bitswan_network
    volumes:
      - ${HOME}/.config/bitswan/dev-gitops/gitops:/repo/gitops
      - ${HOME}/.config/bitswan/dev-gitops/secrets:/repo/secrets
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DEV_GITOPS_SRC}:/src/app
      - /Users/lukasvecerka/.gitconfig:/root/.gitconfig
    environment:
      - BITSWAN_GITOPS_DIR=/repo
      - BITSWAN_GITOPS_DIR_HOST=${HOME}/.config/bitswan/dev-gitops/gitops
      - BITSWAN_GITOPS_SECRET=${DEV_GITOPS_SECRET}
      - BITSWAN_GITOPS_DOMAIN=${DEV_GITOPS_DOMAIN}

networks:
  bitswan_network:
    external: true