services:
  gitops-dev:
    build: .
    restart: always
    privileged: true
    pid: host
    ports:
      - "8079:8079"
    networks:
      - bitswan_network
    volumes:
      - ${HOME}/.config/bitswan/dev-gitops/gitops:/repo/gitops:z
      - ${HOME}/.config/bitswan/dev-gitops/secrets:/repo/secrets:z
      - /var/run/docker.sock:/var/run/docker.sock:z
      - ${DEV_GITOPS_SRC}:/src/app:z
    environment:
      - BITSWAN_GITOPS_DIR=/repo
      - BITSWAN_GITOPS_DIR_HOST=${HOME}/.config/bitswan/dev-gitops
      - BITSWAN_GITOPS_SECRET=${DEV_GITOPS_SECRET}
      - BITSWAN_GITOPS_DOMAIN=${DEV_GITOPS_DOMAIN}
      - DEBUG=true
      - HOST_PATH=$PATH
      - HOST_HOME=$HOME
      - HOST_USER=$USER
      - BITSWAN_USE_HTTPS=${DEV_USE_HTTPS}
      - JUPYTER_SERVER_ALLOWED_ORIGINS=${JUPYTER_SERVER_ALLOWED_ORIGINS}
      - JUPYTER_SERVER_ENABLE_TOKEN_AUTH=${JUPYTER_SERVER_ENABLE_TOKEN_AUTH}
      - JUPYTER_SERVER_DISABLE_XSRF_CHECK=${JUPYTER_SERVER_DISABLE_XSRF_CHECK}

networks:
  bitswan_network:
    external: true
